<div class="home-slider">
	<a href="#">
	<img class="" src="<?php echo Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_MEDIA); ?>wannabe/home-img.png" alt="Homepage" />
	</a>
</div>

<div class="clear home-mid-banner">
     <a href="#">
	 <img class="first" src="<?php echo Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_MEDIA); ?>wannabe/home-1.png" alt="Homepage" />
	 </a>
	 
	 <a href="#">
	 <img class="" src="<?php echo Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_MEDIA); ?>wannabe/home-2.png" alt="Homepage" />
	 </a>
	 
	 <a href="#">
	 <img class="" src="<?php echo Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_MEDIA); ?>wannabe/home-3.png" alt="Homepage" />
	 </a>
</div>



<div class="clear">
<h5 style="float: left; border: 1px solid #EFEFEF; padding: 4px 15px; margin: 13px 0 0 20px; border-bottom: 0;">SALE PRODUCTS</h5>
<div class="clear" style="border-top: 1px solid #EFEFEF; height: 13px;">&nbsp;</div>


