<style>
	#sidebar div:hover {
		background: #FFFFFF !important;
		color: #ee4b85;
		font-weight: bold;
		background-color: rgb(255, 255, 255);
	
	}
	
	#sidebar div {
		padding-bottom: 13px;
		border-bottom: 1px solid #EEEEEE;
		margin-bottom: 13px !important;

	}
</style> 
<script src="http://maps.google.com/maps/api/js?sensor=false" type="text/javascript"></script>


<script>
    var map;
    var markers = [];
    var infoWindow;
    var panorama;

    function init_map() {
        map = new google.maps.Map(document.getElementById("map"), {
            //center: new google.maps.LatLng(10.767923413032847, 106.66383504867554),
            zoom: 4,
            mapTypeId: 'roadmap',
            mapTypeControlOptions: {style: google.maps.MapTypeControlStyle.DROPDOWN_MENU}
        });
        infoWindow = new google.maps.InfoWindow();
	
        var address = $j('#address').val();
        // if(address=='') init_location();
        //    else searchLocations();
        displayLocation();
    }

    function init_location() {
        map = new google.maps.Map(document.getElementById("map"), {
            center: new google.maps.LatLng(10.767923413032847, 106.66383504867554),
            zoom: 15,
            mapTypeId: 'roadmap',
            mapTypeControlOptions: {style: google.maps.MapTypeControlStyle.DROPDOWN_MENU}
        });
    }

    /*  $j("#next").live('click', function(event) {
        event.preventDefault();
        var page_number = $j('body').data("page_number");
        $j('body').data("page_number", (page_number+1));
        searchLocations();
    });
     */
    $j("#previous").live('click', function(event) {
        event.preventDefault();
        var page_number = $j('body').data("page_number");
        $j('body').data("page_number", (page_number-1));
        searchLocations();
    });

    function searchLocations() {
        var address = $j('#address').val();
        var geocoder = new google.maps.Geocoder();
        geocoder.geocode({address: address}, function(results, status) {
            if (status == google.maps.GeocoderStatus.OK) {
                searchLocationsNear(results[0].geometry.location);
            } 
            else {
                alert(address + ' not found');
            }
        });
    }

    function clearLocations() {
        infoWindow.close();
        for (var i = 0; i < markers.length; i++) {
            markers[i].setMap(null);
        }
        markers.length = 0;
	
        var option = document.createElement("option");
        option.value = "none";
        option.innerHTML = "See all results:";
    }

    function createSidebarEntry(markerNum, sidebarContent, markerContent, lat, lng) {
        var div = document.createElement('div');
        div.innerHTML = sidebarContent;
        div.style.cursor = 'pointer';
        div.style.marginBottom = '0px';
	
        div.onclick = function(){
            infoWindow.setContent(markerContent);
            infoWindow.open(map, markers[markerNum]);
            streetView(lat,lng);
        }
	
        div.onmouseover = function(){
            div.style.backgroundColor = '#eee';
        }
	
        div.onmouseout = function(){
            div.style.backgroundColor = '#fff';
        }
	
        return div;
    }

    function resizeMap(width,height) {
        $j('#map').animate({width: width, height:height}, 
        function() { 
            google.maps.event.trigger(map, 'resize');
            map.setCenter(map.getCenter());
        });
    }

    function streetView(lat,lng) {
        var dom = 'streetview';
        panorama = new google.maps.StreetViewPanorama(document.getElementById(dom));
        displayStreetView(lat,lng, dom);
        if($j('#map').height()==600) {
            resizeMap(720,600);
            //$j('#streetview').height(300);
        }
    }

    function searchLocationsNear(center) {
        clearLocations();
	
        var sidebar = document.getElementById('sidebar');
        sidebar.innerHTML = '';
 	
        var page_number = $j('body').data("page_number");
        if(page_number==null) {
            page_number=1;
            $j('body').data("page_number", page_number);
        }
        var categoryid = $j('#categoryid').val();
        //var searchUrl = 'map_data.php?lat=' + center.lat() + '&lng=' + center.lng() + '&categoryid=' + categoryid + '&page_number=' + page_number;
        var searchUrl = '<?php echo Mage::getBaseUrl().'testmap.php' ?>';
        $j.ajax({
            type: 'GET',
            url: searchUrl,
            dataType: 'json',
            success: function(msg) {
                var locations = msg.locations;
                var markersContent = msg.markersContent;
                var sidebarContent = msg.sidebarContent;
                var bounds = new google.maps.LatLngBounds();
                for (var i = 0; i < locations.length; i++) {
                    var name = locations[i]['name'];
                    var address = locations[i]['address'];
                    var distance = parseFloat(locations[i]['distance']);
                    var latlng = new google.maps.LatLng(
                    parseFloat(locations[i]['lat']),
                    parseFloat(locations[i]['lng'])
                );
			
                    var sidebarEntry = createSidebarEntry(i, sidebarContent[i], markersContent[i], locations[i]['lat'], locations[i]['lng']);
                    sidebar.appendChild(sidebarEntry);
			
                    createOption(name, distance, i);
                    createMarker(latlng, locations[i]['lat'], locations[i]['lng'], markersContent[i]);
      
                    bounds.extend(latlng);
                }
                $j('#pagination').html(msg.pagination);
                map.fitBounds(bounds);
            }
        });
        resizeMap(720,600);
        $j('#streetview').html('').height(0);
    }

    function createMarker(latlng, lat, lng, html) {
        var marker = new google.maps.Marker({
            map: map,
            position: latlng,
            animation: google.maps.Animation.DROP
        });
        google.maps.event.addListener(marker, 'click', function() {
            infoWindow.setContent(html);
            infoWindow.open(map, marker);
            streetView(lat,lng);
        });
        markers.push(marker);
    }

    function createOption(name, distance, num) {
        var option = document.createElement("option");
        option.value = num;
        option.innerHTML = name + "(" + distance.toFixed(1) + ")";
    }

    function displayStreetView(lat,lng, dom) {
        var latlng = new google.maps.LatLng(lat,lng);
	
        var panoramaOptions = {
            position: latlng,
            pov: {
                heading: 270,
                pitch: 0,
                zoom: 1
            }
        };
        panorama = new google.maps.StreetViewPanorama(document.getElementById(dom),panoramaOptions);
        map.setStreetView(panorama);
    }

    function processSVData(data, status) {
        marker.setMap();
	
        if (status == google.maps.StreetViewStatus.OK) {
            marker = new google.maps.Marker({
                position: data.location.latLng,
                map: map,
                title: data.location.description
            });
	  
            panorama.setPano(data.location.pano);
            panorama.setPov({
                heading: 270,
                pitch: 0,
                zoom: 1
            });
            panorama.setVisible(true);
	  
            google.maps.event.addListener(marker, 'click', function() {
	  
                var markerPanoID = data.location.pano;
                // Set the Pano to use the passed panoID
                panorama.setPano(markerPanoID);
                panorama.setPov({
                    heading: 270,
                    pitch: 0,
                    zoom: 1
                });
                panorama.setVisible(true);
            });
        } 
        else {
            alert("Street View data not found for this location.");
        }
    }

    function displayLocation() {
        clearLocations();
	
        var sidebar = document.getElementById('sidebar');
        sidebar.innerHTML = '';
 	
        var page_number = $j('body').data("page_number");
        if(page_number==null) {
            page_number=1;
            $j('body').data("page_number", page_number);
        }
        var categoryid = $j('#categoryid').val();
        //var searchUrl = 'map_data.php?lat=' + center.lat() + '&lng=' + center.lng() + '&categoryid=' + categoryid + '&page_number=' + page_number;
        var searchUrl = 'testmap.php';
        $j.ajax({
            type: 'GET',
            url: searchUrl,
            dataType: 'json',
            success: function(msg) {
                var locations = msg.locations;
                var markersContent = msg.markersContent;
                var sidebarContent = msg.sidebarContent;
                var bounds = new google.maps.LatLngBounds();
                for (var i = 0; i < locations.length; i++) {
                    var name = locations[i]['name'];
                    var address = locations[i]['address'];
                    var distance = parseFloat(locations[i]['distance']);
                    var latlng = new google.maps.LatLng(
                    parseFloat(locations[i]['lat']),
                    parseFloat(locations[i]['lng'])
                );
			
                    var sidebarEntry = createSidebarEntry(i, sidebarContent[i], markersContent[i], locations[i]['lat'], locations[i]['lng']);
                    sidebar.appendChild(sidebarEntry);
			
                    createOption(name, distance, i);
                    createMarker(latlng, locations[i]['lat'], locations[i]['lng'], markersContent[i]);
      
                    bounds.extend(latlng);
                }
                // $j('#pagination').html(msg.pagination);
                map.fitBounds(bounds);
            }
        });
        resizeMap(720,600);
        $j('#streetview').html('').height(0);
    }
    $j(document).ready(function() {
        init_map();
        $j('#address').focus();
		
        $j('#streetview2').live('click', function(){
            $j("#streetview2").fancybox();
            return false;
        });
	
    })
</script>
<div>
    <h1 style="font-size: 17px;padding: 2px 0 17px 0; color: #FA198E;"><strong>Hệ Thống Cửa Hàng Wannabe</strong></h1>
    <div>
        <table> 
            <tr>
                <td width="350" valign="top">
                    <div id="sidebar" style="overflow: auto; height: 580px; font-size: 12px; color: #444;padding-right: 25px; "></div>
                    <div id="pagination"></div>
                </td>
                <td>
                    <div id="map" style="overflow: hidden; width:720px; height:600px"></div>
                </td>
            </tr>
        </table>
    </div>

</div>
