<div id="top"></div>
<div class="header-container">
	<div class="header-top-bar">
		<div class="links-content clearfix">
			<ul class="left-links">
				<li><a href="/tin-tuc">Tin Tức Wannabe</a></li>
				<li><a href="/ban-do">Bản đồ Shop</a></li>
			
			</ul>
			<?php echo $this->getChildHtml('topLinks') ?>
		</div>
    </div>
    <div class="header">
        <div class="header-left">
            <?php //echo $this->getChildHtml('store_language') ?>         
            <?php if ($this->getIsHomePage()):?>
            <a href="<?php echo $this->getUrl('') ?>" title="<?php echo $this->getLogoAlt() ?>" class="logo"><img src="<?php echo $this->getLogoSrc() ?>" alt="<?php echo $this->getLogoAlt() ?>" /></a>
            <?php else:?>
            <a href="<?php echo $this->getUrl('') ?>" title="<?php echo $this->getLogoAlt() ?>" class="logo"><strong><?php echo $this->getLogoAlt() ?></strong><img src="<?php echo $this->getLogoSrc() ?>" alt="<?php echo $this->getLogoAlt() ?>" /></a>
            <?php endif?>
        </div>
        <div class="header-center">
        	<div class="hotline">Hotline: <span class="hotline-number">(08) 3820 9030 <span style="color: #666; font-weight: normal; font-size: 12px;">hoặc</span> 0982 098 098</span></div>
            
            <?php echo $this->getChildHtml('topBar') ?>   
        </div>        
        <div class="header-right">
        	<div class="welcome-msg"><?php echo $this->getWelcome() ?></div>
            <div class="minicart">
                <?php echo $this->getChildHtml('top_cart') ?>
            </div>  
            <?php echo $this->getChildHtml('currency') ?>  
            <div class="clear"></div>   
           
        </div>      
    </div>
    <?php echo $this->getChildHtml('topMenu') ?>
    <?php echo $this->getChildHtml('topBread') ?>
    <?php echo $this->getChildHtml('topContainer'); ?>

</div>