    <ul class="form-list checkmo-list" id="payment_form_<?php echo $this->getMethodCode() ?>" style="display:none;">
        <li>

           <div align="right"> <label align="right" style="width:200px"><?php echo 'Tài khoản nhận tiền tại Bảo Kim:'; echo $this->getMethod()->get_email_bussiness() ?></label></div>
        </li>
        <li>
            <address class="checkmo-mailing-address">
             <?php $_SESSION['email_bussiness']=nl2br($this->getMethod()->get_email_bussiness());?>
                <?php $_SESSION['merchant_id']=nl2br($this->getMethod()->get_merchant_id());?>
					 <?php $_SESSION['secure_pass']=nl2br($this->getMethod()->get_secure_pass());?>
					 <?php $_SESSION['url_Success']=nl2br($this->getMethod()->get_url_Success());?>
            <?php $_SESSION['total_amount']=Mage::getSingleton('checkout/cart')->getQuote()->getGrandTotal(); ?>
                
            </address>
        </li>
    </ul>
