<?php

$bannerGroupCode = $this->getBannerGroupCode();
$data = $this->getGroupCodeData();
$bannerGroupData = $data['group_data'];
$bannerData = $data['banner_data'];
$mediaDir = Mage::getBaseDir('media');
$bannerdest = (($bannerGroupData->getLinkTarget() == 0) ? '_blank' : '_self');

if(count($bannerData)>0):
    echo '<div class="clearfix home-mid-banner">';
    foreach ($bannerData as $banner):
        $bannerType = $banner->getBannerType();
        if ($bannerType == 1) : // banner type HTML
            echo '<div' . $banner->getBannerContent().'</div>';
        else:
            if($banner->getFilename() != '' && @file_exists($mediaDir . DS . $banner->getFilename())):
                $bannerImage = $this->getResizeImage($banner->getFilename(), $bannerGroupCode, $bannerGroupData->getBannerWidth(), $bannerGroupData->getBannerHeight());
                echo '<a target="'.$bannerdest.'" title="'.$banner->getTitle().'" href="'.$banner->getLink().'">';
                  echo '<img title="'.$banner->getTitle().'" alt="'.$banner->getTitle().'" src="'.$bannerImage.'" class="SSDF"></a>';
            
            endif;
        endif;
    endforeach;
    echo "</div>";
endif;
?>
