<div style="clear: both;"></div>
<?php
if (($_products = $this->getProductCollection()) && $_products->getSize()): ?>
	
	<h2 class="home-bestseller">
		<a href="<?php echo $this->getLink();?>"><?php echo $this->getTitle();?></a>
                
	</h2>	

    <div class="saleproducts saleproducts-<?php echo $this->getCategoryId(); ?>">
        <div class="carousel-<?php echo $this->getCategoryId(); ?> carousel">
            <div class="slider">
                <?php $i=0; foreach ($_products->getItems() as $_product): $i++; ?>
                    <div class="slide <?php if(($i == 4 && $_products->getSize() < 5) || ($i == $_products->getSize())) echo 'last'?>"> 
                        <?php include('view/labels.phtml')  ?>    
                        <?php echo $this->getReviewsSummaryHtml($_product, 'short') ?>          
                        <a href="<?php echo $_product->getProductUrl() ?>" title="<?php echo $this->htmlEscape($_product->getName()) ?>" class="product-image"><img src="<?php echo $this->helper('catalog/image')->init($_product, 'small_image')->resize(182,255) ?>"  alt="<?php echo $this->htmlEscape($_product->getName()) ?>" /></a>
                        <div class="new-description">
                            <h3><a href="<?php echo $_product->getProductUrl() ?>" title="<?php echo $this->htmlEscape($_product->getName()) ?>"><?php echo $this->htmlEscape($_product->getName()) ?></a></h3>
                            <?php echo $this->getPriceHtml($_product, true) ?>                    
                        
                            <?php if($_product->isSaleable()): ?>
                                
                            <?php else: ?>
                                <p class="availability out-of-stock"><span><?php echo $this->__('Out of stock') ?></span></p>
                            <?php endif; ?>
                            <div style="clear: both;"></div>
                        </div>                    
                    </div>
                <?php endforeach; ?>
            </div>             
        </div>
        <?php if($_products->getSize() >= 5): ?>
            <div class="prev sale-arrow">&nbsp;</div>
            <div class="next sale-arrow">&nbsp;</div>  
        <?php endif; ?>
    </div>     
    <div style="clear: both;"></div>
    <?php if($_products->getSize() >= 5): ?>
        <script type="text/javascript">
            jQuery('.saleproducts-<?php echo $this->getCategoryId(); ?> .sale-arrow.prev').addClass('disabled');
            jQuery('.saleproducts-<?php echo $this->getCategoryId(); ?> .carousel-<?php echo $this->getCategoryId(); ?>').iosSlider({
                desktopClickDrag: true,
                snapToChildren: true,
                infiniteSlider: false,
                navNextSelector: '.saleproducts-<?php echo $this->getCategoryId(); ?> .sale-arrow.next',
                navPrevSelector: '.saleproducts-<?php echo $this->getCategoryId(); ?> .sale-arrow.prev',
                lastSlideOffset: 3,
                onFirstSlideComplete: function(){
                    jQuery('.saleproducts-<?php echo $this->getCategoryId(); ?> .sale-arrow.prev').addClass('disabled');
                },
                onLastSlideComplete: function(){
                    jQuery('.saleproducts-<?php echo $this->getCategoryId(); ?> .sale-arrow.next').addClass('disabled');
                },
                onSlideChange: function(){
                    jQuery('.saleproducts-<?php echo $this->getCategoryId(); ?> .sale-arrow.prev').removeClass('disabled');
                    jQuery('.saleproducts-<?php echo $this->getCategoryId(); ?> .sale-arrow.next').removeClass('disabled');
                }
            });               
        </script>    
    <?php endif; ?>
<?php endif; ?>