<?php $_helper = $this->helper('catalog/output'); ?>

<?php $_product = $this->getProduct(); ?>

<?php $_layout = themeOptions('layout'); ?>



<script type="text/javascript">

    var optionsPrice = new Product.OptionsPrice(<?php echo $this->getJsonConfig() ?>);

</script>

<a class="back-to" href="javascript: history.go(-1)"><?php echo $this->__('Return to Previous Page') ?></a>

        

<div id="messages_product_view"><?php echo $this->getMessagesBlock()->getGroupedHtml() ?></div>

<div class="product-view layout_<?php echo $_layout ?>">

    <div class="product-essential">

    <form action="<?php echo $this->getSubmitUrl($_product) ?>" method="post" id="product_addtocart_form"<?php if($_product->getOptions()): ?> enctype="multipart/form-data"<?php endif; ?>>

        <div class="no-display">

            <input type="hidden" name="product" value="<?php echo $_product->getId() ?>" />

            <input type="hidden" name="related_product" id="related-products-field" value="" />

        </div>

        <div id="addedoverlay" style='display:none'> </div>

        <div id='added' style='display:none'></div>

        <div id='productname' style='display:none'><?php echo $_helper->productAttribute($_product, $_product->getName(), 'name') ?></div>

        <div class="product-img-box">

      
		
		<?php echo $this->getChildHtml('media') ?>
	     	     			
        </div>
	

        <div class="product-shop">

            <div class="white-back">

                <div class="product-name">

                    <h2><?php echo $_helper->productAttribute($_product, $_product->getName(), 'name') ?></h2>


                       


			
                </div>

                <!--Facebook like button code starts here  -->
                       
	 
					<?php $CurrentUrl = urlencode(Mage::helper('core/url')->getCurrentUrl()); ?>  
					<iframe src="http://facebook.com/plugins/like.php?href=<?php echo $CurrentUrl; ?>&layout=standard&amp;width=450&amp;show_faces=false&amp;font&amp;colorscheme=light&amp;action=like&amp;height=80&amp;appId=230850210394176" 
					scrolling="no" frameborder="0" style="border:none; overflow:hidden; width:374px; height:30px; left: 0px;" allowTransparency="true"></iframe>
				
				 	<!--Facebook like button code ends here  -->

				 </div>
			                
                <!--<?php echo $this->getReviewsSummaryHtml($_product, false, true)?> -->

                <?php echo $this->getChildHtml('alert_urls') ?>

                <?php echo $this->getChildHtml('extrahint') ?>

                <?php if($_product->getTypeId() != 'bundle'): ?>

                    <?php echo $this->getPriceHtml($_product) ?>

                <?php else: ?>

                    <?php echo $this->__('Product code:').'<strong>'.$_product->getSku().'</strong>'; ?>

                    <?php echo $this->getChildHtml('product_type_data') ?>

                <?php endif;?>

                

                <div class="addtocont">

                    <?php if($_product->getTypeId() != 'bundle'): ?>

                        <span class="product-code"><?php echo $this->__('Product code:').' <strong>'.$_product->getSku().'</strong>'; ?></span>

                        <?php echo $this->getChildHtml('product_type_data') ?>

                    <?php endif;?>

                    <?php //echo $this->getLayout()->createBlock('cms/block')->setBlockId('productview')->toHtml(); ?>

                </div>

                <div class="clear"></div>

                <?php echo $this->getTierPriceHtml() ?>

                <?php if ($_product->getShortDescription()):?>

                    <div class="short-description">

                        <p><?php echo $this->__('Quick Overview:') ?></p>

                        <div class="std"><?php echo $_helper->productAttribute($_product, nl2br($_product->getShortDescription()), 'short_description') ?></div>

                    </div>

                <?php endif;?>

		

                <?php if ($_product->isSaleable() && $this->hasOptions()):?>

                    <div id="container1"><?php echo $this->getChildChildHtml('container1', '', true, true) ?><div class="clear"></div></div>

                <?php endif;?>  

                       <?php if ($_product->isSaleable() && $this->hasOptions()):?>
                <div id="container2"><?php echo $this->getChildChildHtml('container2', '', true, true) ?></div> 
   <?php endif;?>  
                

                <?php echo $this->getChildHtml('product_type_data_grouped') ?>

                <?php if (!$this->hasOptions()):?>

                    <div class="add-to-box">

                        <?php if($_product->isSaleable()): ?>

                            <?php echo $this->getChildHtml('addtocart') ?>

                            <?php if( $this->helper('wishlist')->isAllow() || $_compareUrl=$this->helper('catalog/product_compare')->getAddUrl($_product)): ?>

                                <span class="or"><?php echo $this->__('OR') ?></span>

                            <?php endif; ?>

                        <?php endif; ?>

                        <?php echo $this->getChildHtml('addto') ?>

                    </div>



                <?php endif; ?>

		

		  

                <?php if($_layout == 'horizontal'): ?>

                    <div class="clear"></div> 

                    <?php $use_share = themeOptions('use_share'); ?>

                    <?php $share_code = themeOptions('share_code'); ?>

                    <?php if($use_share && $share_code): ?>  

                        <?php echo $share_code; ?>

                    <?php endif; ?>

                <?php endif; ?>  

                

                <?php echo $this->getChildHtml('other');?>



            </div>



            <?php if($_layout != 'horizontal'): ?>

                <div class="product_right">

                    <?php if(themeOptions('brand')): ?>

						<?php $brand_attr = themeOptions('brand_attr'); ?>

                        <?php if ($_product->getData($brand_attr)):  ?>

                            <?php

							$brandImageExt = trim(themeOptions('brand_image_extension'));

							$brandPageBasePath = trim(themeOptions('brand_page_base_path')); 

							$brandLinkSearch = themeOptions('brand_link_search_enabled');

							$attr = $_product->getResource()->getAttribute($brand_attr);	

							$brandValue = trim($attr->getFrontend()->getValue($_product));	

							$brandValueCode = str_replace(" ", "_", strtolower($brandValue));	

							$brandLabel = $attr->getStoreLabel();							

							$brandImageUrl = Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_MEDIA) . 'wysiwyg/blanco/attributes/' . $brand_attr . '/' . $brandValueCode . '.' . $brandImageExt;



							if ($brandLinkSearch)

								$brandPageUrl = Mage::getUrl() . 'catalogsearch/result/?q=' . $brandValue;

							elseif ($brandPageBasePath != '')

							{

								$basePath = ($brandPageBasePath == '/') ? '' : $brandPageBasePath . '/';

								$brandPageUrl = Mage::getUrl() . $basePath . str_replace(" ", "-", strtolower($brandValue));

							}

							else

								$brandPageUrl = '';



							?>

                            <div class="brand-logo">

                            	<?php if ($brandPageUrl != ''): ?>

                                	<a href="<?php echo $brandPageUrl;?>" title="<?php echo str_replace("%s", $brandValue, $this->__('Click to see more products from %s')); ?>"><img src="<?php echo $brandImageUrl;?>" alt="<?php echo $brandValue; ?>" width="145" height="50" /></a>

                                <?php else: ?>

                                	<img src="<?php echo $brandImageUrl;?>" title="<?php echo $brandLabel .': '. $brandValue; ?>" alt="<?php echo $brandValue; ?>" width="145" height="50" />

                                <?php endif; ?>

                            </div>

                        <?php endif; ?>

                    <?php endif; ?>

                                    
                    <?php echo $this->getLayout()->createBlock('cms/block')->setBlockId('productview')->toHtml(); ?>

                    <?php $use_share = themeOptions('use_share'); ?>

                    <?php $share_code = themeOptions('share_code'); ?>

                    <?php if($use_share && $share_code): ?>  

                        <?php echo $share_code; ?>

                    <?php endif; ?>

                </div>

            <?php endif; ?>

                   <?php if ($_product->isSaleable() && $this->hasOptions()):?>
               </div>

            

        <?php endif;?>


        </div>

        <div class="clearer"></div>

 

    </form>



    <script type="text/javascript">

    //<![CDATA[

        var productAddToCartForm = new VarienForm('product_addtocart_form');

		var url = jQuery('#product_addtocart_form').attr('action');

		url = url.replace("checkout/cart","ajax/index");    



        var msgHtml;

        var productImg = jQuery('.main-thumbnail').html();

        var windowOver = jQuery('#addedoverlay');

        var windowBox = jQuery('#added');

        var titleForBox = jQuery('#productname').text();   

        var data = {'isAjax':1}

        

        /*jQuery('#product_addtocart_form').ajaxForm({

            url: url,

            data: data,

            dataType: 'json',

            beforeSubmit: function(){    

                if(productAddToCartForm.validator.validate()){

                    windowOver.show();

                    windowBox.show().css({

                        backgroundImage: "url('<?php echo $this->getSkinUrl('images/loading.gif')?>')"

                    });                    

                }else{

                    return false;

                }

            },

            error: function(data){

	            windowBox.css({

       			      backgroundImage: 'none'

                }).html('<?php echo $this->__('Error') ?>');					   

                windowOver.one('click',function(){

		            hidewindow(windowBox,windowOver);                    

                });	       

                                 

                jQuery('#hidewindow').click(function(){

		            hidewindow(windowBox,windowOver);                    

                });

            },

            success : function(data,statusText,xhr ){

                if(data.status == 'SUCCESS'){

                    if(jQuery('.block-cart')){

                        jQuery('.block-cart').replaceWith(data.sidebar);

                    }

                    if(jQuery('.header .block-cart-header')){

                        jQuery('.header .block-cart-header').replaceWith(data.topcart);

                    }     

                    msgHtml = '<div class="added-content"><div class="checkout-content"><em>' + titleForBox + '</em> <?php echo $this->__('was successfully added to your shopping cart.') ?></div><div style="clear:both;"></div><a id="hidewindow" href="javascript:void(0);"><?php echo $this->__('Continue shopping') ?></a>&nbsp;<a href="<?php echo $this->getUrl('checkout/cart')?>"><?php echo $this->__('View cart & checkout') ?></a></div>';             

                }else{

                    msgHtml = '<div class="added-content"><p class="error-msg" style="margin-bottom:15px;">' + data.message + '</p><a id="hidewindow" href="javascript:void(0);"><?php echo $this->__('Continue shopping') ?></a>&nbsp;<a href="<?php echo $this->getUrl('checkout/cart')?>"><?php echo $this->__('View cart & checkout') ?></a></div>';

                }					   

               

                windowBox.css({

       			      backgroundImage: 'none'

                }).html(msgHtml);					   

                windowOver.one('click',function(){

    	            hidewindow(windowBox,windowOver);                    

                });	       

                                 

                jQuery('#hidewindow').click(function(){

    	            hidewindow(windowBox,windowOver);                    

                });	   

            }

        }); */

        

        function hidewindow(windowBox,windowOver){

            windowOver.fadeOut(400);

            windowBox.fadeOut(400).html('');	

        }



    //]]>

    </script>

    </div>



    <div class="product-collateral">

        <?php echo $this->getChildHtml('info_tabs') ?>

        <?php echo $this->getChildHtml('product_additional_data') ?>

    </div>

        <?php echo $this->getChildHtml('related_products') ?>

        <?php echo $this->getChildHtml('upsell_products') ?>

</div>

