<?php

$bannerGroupCode = $this->getBannerGroupCode();
////$data = $this->getDataByGroupCode($bannerGroupCode);
$data = $this->getGroupCodeData();
$data = $this->getGroupCodeData();
$bannerGroupData = $data['group_data'];
$bannerData = $data['banner_data'];
$mediaDir = Mage::getBaseDir('media');
$bannerdest = (($bannerGroupData->getLinkTarget() == 0) ? '_blank' : '_self');

if(count($bannerData)>0):
    foreach ($bannerData as $banner):
        $bannerType = $banner->getBannerType();
        if ($bannerType == 1) : // banner type HTML
            echo '<div' . $banner->getBannerContent().'</div>';
        else:
            if($banner->getFilename() != '' && @file_exists($mediaDir . DS . $banner->getFilename())):
                $bannerImage = $this->getResizeImage($banner->getFilename(), $bannerGroupCode, $bannerGroupData->getBannerWidth(), $bannerGroupData->getBannerHeight());
		$event = '_gaq.push([\'_trackPageview\',\'/banner-click/manypages/middle_right/'.$banner->getTitle().'\']);';
                echo '<div><a onclick="'.$event.'" target="'.$bannerdest.'" title="'.$banner->getTitle().'" href="'.$banner->getLink().'">';
                echo '<img width="'.$bannerGroupData->getBannerWidth().'px"  title="'.$banner->getTitle().'" alt="'.$banner->getTitle().'" src="'.$bannerImage.'"></a></div>';
            endif;
        endif;
    endforeach;
endif;
?>