<?php
/**
 * aheadWorks Co.
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the EULA
 * that is bundled with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * http://ecommerce.aheadworks.com/AW-LICENSE.txt
 *
 * =================================================================
 *                 MAGENTO EDITION USAGE NOTICE
 * =================================================================
 * This package designed for Magento community edition
 * aheadWorks does not guarantee correct work of this extension
 * on any other Magento edition except Magento community edition.
 * aheadWorks does not provide extension support in case of
 * incorrect edition usage.
 * =================================================================
 *
 * @category   AW
 * @package    AW_Blog
 * @version    1.2.1
 * @copyright  Copyright (c) 2010-2012 aheadWorks Co. (http://www.aheadworks.com)
 * @license    http://ecommerce.aheadworks.com/AW-LICENSE.txt
 */
?> 
<?php $posts = $this->getPosts(); ?>
<div id="messages_product_view">
    <?php Mage::app()->getLayout()->getMessagesBlock()->setMessages(Mage::getSingleton('customer/session')->getMessages(true)); ?> 
    <?php echo Mage::app()->getLayout()->getMessagesBlock()->getGroupedHtml(); ?> 
</div>

<?php foreach ($posts as $post): ?>
    <div class="postWrapper">
        <div class="postTitle">
            <h2><a href="<?php echo $post->getAddress(); ?>" ><?php echo $post->getTitle(); ?></a></h2>
            <h3>
                <?php echo $post->getCreatedTime(); ?>
                <span class="postDetails">
                    <?php if ($this->getCommentsEnabled()): ?>
                    <?php echo $post->getCommentCount(); ?> <a href="<?php echo $post->getAddress(); ?>#commentBox" >Comments</a> | 
                <?php endif; ?>
                <?php $postCats = $post->getCats(); ?>
                <?php if (!empty($postCats)): ?>
                <?php echo Mage::helper('blog')->__('gửi trong'); ?>
                <?php foreach ($postCats as $data): ?>               
                <a href="<?php echo $data['url']; ?>"><?php echo $data['title']; ?></a> 
            <?php endforeach; ?> 
        <?php else: ?>
        <?php echo Mage::helper('blog')->__('Posted'); ?>
    <?php endif; ?><?php echo $this->__("bởi"); ?> <?php echo $post->getUser(); ?></span>

            </h3>
        </div>
        <div class="postContent clearfix">
		<?php if($post->getFilename()): ?>
		<a href="<?php echo $post->getAddress(); ?>" >
			<img src="<?php echo  Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_MEDIA).'/'.$post->getFilename();?>" alt="<?php echo $data['title']; ?>" style="width:100px;height:100px; float:left; margin-right:10px">
		</a>
		<?php endif; ?>	
			<?php echo $post->getPostContent(); ?>
		</div>

        <?php echo $this->getBookmarkHtml($post) ?>
        <div class="tags"><?php echo $this->getTagsHtml($post) ?></div>
    </div>
        
<?php endforeach; ?> 

<?php echo $this->getChildHtml('aw_blog_comments_toolbar'); ?>
<?php //$this->getPages(); ?>
