<?php

$bannerGroupCode = $this->getBannerGroupCode();
$data = $this->getDataByGroupCode($bannerGroupCode);
$bannerGroupData = $data['group_data'];
$template = '';
if (count($bannerGroupData) > 0):
    $prebaneff = $bannerGroupData->getPreBannerEffects();
    $bannerType = $bannerGroupData->getAnimationType();
?>
<?php
    if ($bannerType == 1):
        $template = $this->getLayout()->createBlock('banner/banner', 'home.top.banner.custom')->setBannerGroupCode($bannerGroupCode)->setGroupCodeData($data)->setTemplate('banner/home/top/effects/custom.phtml')->toHtml();
    else:
        switch ($prebaneff) {
            case 'Image Slide Show':
                $template = $this->getLayout()->createBlock('banner/banner', 'home.top.banner.slideshow')->setBannerGroupCode($bannerGroupCode)->setGroupCodeData($data)->setTemplate('banner/home/top/effects/slideshow.phtml')->toHtml();
                break;
            case 'Square Transition Banner':
                $template = $this->getLayout()->createBlock('banner/banner', 'home.top.banner.strans')->setBannerGroupCode($bannerGroupCode)->setGroupCodeData($data)->setTemplate('banner/home/top/effects/strans.phtml')->toHtml();
                break;
            case 'Image Simple':
                $template = $this->getLayout()->createBlock('banner/banner', 'home.top.banner.imagesimple')->setBannerGroupCode($bannerGroupCode)->setGroupCodeData($data)->setTemplate('banner/home/top/effects/imagesimple.phtml')->toHtml();
                break;
            default :
               $template = $this->getLayout()->createBlock('banner/banner', 'home.top.banner.slideshow')->setBannerGroupCode($bannerGroupCode)->setGroupCodeData($data)->setTemplate('banner/home/top/effects/slideshow.phtml')->toHtml();
               break;
        }
    endif;
    echo $template;
endif;
?>