<!--
/**
 * Unicode Systems
 * @category   Uni
 * @package    Uni_Upload
 * @copyright  Copyright (c) 2010-2011 Unicode Systems. (http://www.unicodesystems.in)
 * @license    http://opensource.org/licenses/afl-3.0.php  Academic Free License (AFL 3.0)
 */
-->
<?php echo $this->getTabsHtml() ?>
<script type="text/javascript">
    //<![CDATA[
    function load_upload_funcs(){        
<?php if (($block = $this->getLayout()->getBlock('uploadgroup.grid.upload')) && ($_gridJsObject = $block->getJsObjectName())): ?>
            if(!$('in_uploadgroup_uploads')){
                setTimeout('load_upload_funcs()',500);
                return false;
            }
            var selectedUploads=$H(<?php echo $this->getUploadsJson(); ?>);            
            $('in_uploadgroup_uploads').value = selectedUploads.toQueryString();
            
            function registerSelectedUpload(grid, element, checked){
                if(checked){
                    selectedUploads.set(element.value, element.value);
                }
                else{
                    selectedUploads.unset(element.value);
                }
                $('in_uploadgroup_uploads').value = selectedUploads.toQueryString();                
                grid.reloadParams = {'selected_uploads[]':selectedUploads.keys()};
            }    
            function selectedUploadRowClick(grid, event){
                var trElement = Event.findElement(event, 'tr');
                var isInput   = Event.element(event).tagName == 'INPUT';
                if(trElement){
                    var checkbox = Element.getElementsBySelector(trElement, 'input');
                    if(checkbox[0]){
                        var checked = isInput ? checkbox[0].checked : !checkbox[0].checked;
<?php echo $_gridJsObject ?>.setCheckboxChecked(checkbox[0], checked);
                    }
                }
            }

            var tabIndex = 1000;
            function selectedUploadRowInit(grid, row){
                var checkbox = $(row).getElementsByClassName('checkbox')[0];
            }


<?php echo $_gridJsObject ?>.rowClickCallback 		= selectedUploadRowClick;
<?php echo $_gridJsObject ?>.initRowCallback 		= selectedUploadRowInit;
<?php echo $_gridJsObject ?>.checkboxCheckCallback	= registerSelectedUpload;
<?php echo $_gridJsObject ?>.rows.each(function(row){selectedUploadRowInit(<?php echo $_gridJsObject ?>, row)});

<?php endif; ?>
    }
    load_upload_funcs();
    //]]>
</script>